name: Build iOS App

on:
  push:
    branches: [ "main" ] 
  workflow_dispatch: 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-ios:
    runs-on: macos-latest 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # <-- Yahan 18 se 20 kar diya hai

    - name: Install Dependencies
      run: npm install

    - name: Build Web App (Vite)
      run: npm run build

    - name: Sync Capacitor iOS
      run: npx cap sync ios

    - name: Build unsigned IPA
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos build CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" -derivedDataPath build
        cd build/Build/Products/Release-iphoneos
        mkdir Payload
        cp -r App.app Payload/
        zip -r app.ipa Payload

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-unsigned
        path: ios/App/build/Build/Products/Release-iphoneos/app.ipa
